// apps/reference/src/routes/(app)/docs/create/+page.svelte
<script lang="ts">
  import type { ActionData } from './$types';

  let { form }: { form: ActionData } = $props();
</script>

<svelte:head>
  <title>Create Documentation Site — Snaplify</title>
</svelte:head>

<section class="create-docs-page">
  <h1 class="page-title">Create Documentation Site</h1>

  {#if form?.error}
    <div class="error-message" role="alert">{form.error}</div>
  {/if}

  <form method="POST" class="create-form">
    <div class="form-field">
      <label for="name" class="form-label">Name</label>
      <input
        id="name"
        name="name"
        type="text"
        required
        maxlength="128"
        class="form-input"
        aria-required="true"
      />
    </div>

    <div class="form-field">
      <label for="description" class="form-label">Description (optional)</label>
      <textarea
        id="description"
        name="description"
        maxlength="2000"
        class="form-textarea"
        rows="3"
      ></textarea>
    </div>

    <button type="submit" class="form-submit">Create Site</button>
  </form>
</section>

<style>
  .create-docs-page {
    max-width: var(--layout-narrow-width, 640px);
    margin: 0 auto;
    padding: var(--space-md, 1rem);
  }

  .page-title {
    font-size: var(--font-size-2xl, 1.875rem);
    margin-bottom: var(--space-lg, 2rem);
    color: var(--color-text, inherit);
  }

  .error-message {
    padding: var(--space-sm, 0.5rem);
    margin-bottom: var(--space-md, 1rem);
    border: 1px solid var(--color-danger, #ef4444);
    border-radius: var(--radius-sm, 0.25rem);
    color: var(--color-danger, #ef4444);
    font-size: var(--font-size-sm, 0.875rem);
  }

  .create-form {
    display: flex;
    flex-direction: column;
    gap: var(--space-md, 1rem);
  }

  .form-field {
    display: flex;
    flex-direction: column;
    gap: var(--space-xs, 0.25rem);
  }

  .form-label {
    font-size: var(--font-size-sm, 0.875rem);
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, inherit);
  }

  .form-input,
  .form-textarea {
    padding: var(--space-sm, 0.5rem);
    border: 1px solid var(--color-border, #e5e7eb);
    border-radius: var(--radius-sm, 0.25rem);
    font-size: var(--font-size-sm, 0.875rem);
    color: var(--color-text, inherit);
    background: var(--color-bg-surface, #fff);
  }

  .form-submit {
    padding: var(--space-sm, 0.5rem) var(--space-md, 1rem);
    background: var(--color-primary, #3b82f6);
    color: var(--color-on-primary, #fff);
    border: none;
    border-radius: var(--radius-sm, 0.25rem);
    font-size: var(--font-size-sm, 0.875rem);
    font-weight: var(--font-weight-medium, 500);
    cursor: pointer;
    align-self: flex-start;
  }

  .form-submit:hover {
    opacity: 0.9;
  }
</style>

// apps/reference/pages/hubs/create.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

useSeoMeta({
  title: 'Create Hub — CommonPub',
  description: 'Create a new maker hub.',
});

const name = ref('');
const description = ref('');
const saving = ref(false);
const error = ref('');

async function handleCreate(): Promise<void> {
  saving.value = true;
  error.value = '';
  try {
    const result = await $fetch('/api/hubs', {
      method: 'POST',
      body: { name: name.value, description: description.value },
    });
    await navigateTo(`/hubs/${(result as { slug: string }).slug}`);
  } catch (err: unknown) {
    error.value = (err as { data?: { message?: string } })?.data?.message || 'Failed to create hub.';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="create-community-page">
    <h1 class="page-title">Create Hub</h1>

    <form class="community-form" @submit.prevent="handleCreate" aria-label="Create community form">
      <div v-if="error" class="form-error" role="alert">{{ error }}</div>

      <div class="form-field">
        <label for="community-name" class="form-label">Name</label>
        <input id="community-name" v-model="name" type="text" class="form-input" required placeholder="Hub name" />
      </div>

      <div class="form-field">
        <label for="community-desc" class="form-label">Description</label>
        <textarea id="community-desc" v-model="description" class="form-textarea" rows="3" placeholder="What is this community about?" />
      </div>

      <button type="submit" class="cpub-btn-primary" :disabled="saving || !name">
        {{ saving ? 'Creating...' : 'Create Hub' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.create-community-page {
  max-width: 600px;
}

.page-title {
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--space-6);
}

.community-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.form-error {
  padding: var(--space-3);
  background: var(--red-bg, var(--surface2));
  color: var(--red, var(--text));
  border: 1px solid var(--red, var(--border));
  font-size: var(--text-sm);
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.form-label {
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
}

.form-input,
.form-textarea {
  padding: var(--space-2) var(--space-3);
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--text);
  font-size: var(--text-base);
  font-family: var(--font-sans);
}

.form-input:focus,
.form-textarea:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: var(--focus-ring);
}

.form-textarea {
  resize: vertical;
}

.cpub-btn-primary {
  padding: var(--space-2) var(--space-4);
  background: var(--accent);
  color: var(--color-on-primary);
  border: 1px solid var(--border);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  font-family: var(--font-sans);
  cursor: pointer;
  align-self: flex-start;
}

.cpub-btn-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.cpub-btn-primary:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}
</style>
