// apps/reference/src/routes/(app)/learn/[slug]/[lessonSlug]/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import LessonViewer from '$lib/components/learning/LessonViewer.svelte';
  import LessonNav from '$lib/components/learning/LessonNav.svelte';
  import ProgressBar from '$lib/components/learning/ProgressBar.svelte';
  import { enhance } from '$app/forms';
  import type { PageData, ActionData } from './$types';

  let { data, form }: { data: PageData; form: ActionData } = $props();

  const lesson = data.lesson;
  const completedSet = new Set(data.completedIds);
  const isCompleted = completedSet.has(lesson.id);
</script>

<SeoHead
  title={`${lesson.title} — ${data.path.title}`}
  description=""
  type="Course"
  url={`/learn/${data.path.slug}/${lesson.slug}`}
/>

<article class="lesson-page">
  <nav class="lesson-breadcrumb" aria-label="Breadcrumb">
    <a href="/learn">Learn</a>
    <span aria-hidden="true">/</span>
    <a href="/learn/{data.path.slug}">{data.path.title}</a>
    <span aria-hidden="true">/</span>
    <span aria-current="page">{lesson.title}</span>
  </nav>

  {#if data.enrollment}
    <ProgressBar value={Number(data.enrollment.progress)} label="Path progress" />
  {/if}

  <header class="lesson-header">
    <span class="lesson-type">{lesson.type}</span>
    <h1>{lesson.title}</h1>
  </header>

  <div class="lesson-content">
    <LessonViewer {lesson} />
  </div>

  {#if data.enrollment && !isCompleted}
    <form method="POST" action="?/complete" use:enhance class="complete-form">
      <button type="submit" class="btn btn-primary">Mark as Complete</button>
    </form>
  {:else if isCompleted}
    <div class="completed-badge" role="status">Completed</div>
  {/if}

  {#if form?.certificateIssued}
    <div class="certificate-notice" role="alert">
      Congratulations! You've earned a certificate for completing this path.
      <a href="/dashboard/learning">View your certificates</a>
    </div>
  {/if}

  <LessonNav
    prevLesson={data.prevLesson}
    nextLesson={data.nextLesson}
    pathSlug={data.path.slug}
  />
</article>

<style>
  .lesson-page {
    max-width: var(--layout-content-width, 768px);
    margin: 0 auto;
  }

  .lesson-breadcrumb {
    display: flex;
    gap: var(--space-xs, 0.25rem);
    font-size: var(--font-size-sm, 0.875rem);
    color: var(--color-text-secondary, #666);
    margin-bottom: var(--space-md, 1rem);
  }

  .lesson-breadcrumb a {
    color: var(--color-primary, #2563eb);
    text-decoration: none;
  }

  .lesson-header {
    margin-bottom: var(--space-lg, 2rem);
  }

  .lesson-type {
    display: inline-block;
    padding: var(--space-xs, 0.25rem) var(--space-sm, 0.5rem);
    background: var(--color-surface-secondary, #f5f5f5);
    border-radius: var(--radius-sm, 4px);
    font-size: var(--font-size-xs, 0.75rem);
    text-transform: uppercase;
    color: var(--color-text-secondary, #666);
    margin-bottom: var(--space-sm, 0.5rem);
  }

  .lesson-header h1 {
    font-size: var(--font-size-2xl, 1.875rem);
    color: var(--color-text, #1a1a1a);
    margin: 0;
  }

  .lesson-content {
    margin-bottom: var(--space-xl, 3rem);
    line-height: 1.7;
    color: var(--color-text, #1a1a1a);
  }

  .complete-form {
    margin-bottom: var(--space-lg, 2rem);
  }

  .btn {
    padding: var(--space-sm, 0.5rem) var(--space-lg, 2rem);
    border: none;
    border-radius: var(--radius-md, 6px);
    font-size: var(--font-size-md, 1rem);
    cursor: pointer;
  }

  .btn-primary {
    background: var(--color-primary, #2563eb);
    color: var(--color-on-primary, #ffffff);
  }

  .completed-badge {
    display: inline-block;
    padding: var(--space-sm, 0.5rem) var(--space-md, 1rem);
    background: var(--color-success-bg, #f0fdf4);
    color: var(--color-success, #22c55e);
    border-radius: var(--radius-md, 6px);
    font-weight: var(--font-weight-medium, 500);
    margin-bottom: var(--space-lg, 2rem);
  }

  .certificate-notice {
    padding: var(--space-md, 1rem);
    background: var(--color-success-bg, #f0fdf4);
    color: var(--color-success, #22c55e);
    border-radius: var(--radius-md, 6px);
    margin-bottom: var(--space-lg, 2rem);
  }

  .certificate-notice a {
    color: var(--color-primary, #2563eb);
    font-weight: var(--font-weight-medium, 500);
  }
</style>

// apps/reference/pages/learn/[slug]/[lessonSlug].vue
<script setup lang="ts">
const route = useRoute();
const slug = computed(() => route.params.slug as string);
const lessonSlug = computed(() => route.params.lessonSlug as string);

const { data: lesson } = await useFetch(() => `/api/learn/${slug.value}/${lessonSlug.value}`);

useSeoMeta({
  title: () => lesson.value ? `${lesson.value.title} — CommonPub` : 'Lesson — CommonPub',
});

const { isAuthenticated } = useAuth();
const toast = useToast();
const completing = ref(false);
const completed = ref(false);

async function markComplete(): Promise<void> {
  completing.value = true;
  try {
    await $fetch(`/api/learn/${slug.value}/${lessonSlug.value}/complete`, { method: 'POST' });
    completed.value = true;
    toast.success('Lesson completed!');
  } catch {
    toast.error('Failed to mark as complete');
  } finally {
    completing.value = false;
  }
}
</script>

<template>
  <div class="lesson-page" v-if="lesson">
    <NuxtLink :to="`/learn/${slug}`" class="cpub-back-link">Back to path</NuxtLink>

    <header class="lesson-header">
      <span class="lesson-type">{{ lesson.type }}</span>
      <h1 class="lesson-title">{{ lesson.title }}</h1>
      <span v-if="lesson.duration" class="lesson-duration">{{ lesson.duration }} min</span>
    </header>

    <div class="lesson-content">
      <!-- Render markdown content if available -->
      <div v-if="lesson.content" class="cpub-prose" v-html="lesson.content" />
      <!-- Video embed if lesson has a videoUrl -->
      <div v-else-if="lesson.videoUrl" class="lesson-video">
        <iframe :src="lesson.videoUrl" frameborder="0" allowfullscreen style="width: 100%; aspect-ratio: 16/9;" />
      </div>
      <div v-else class="lesson-empty">
        <i class="fa-solid fa-book-open" style="font-size: 24px; color: var(--text-faint);"></i>
        <p>This lesson has no content yet.</p>
      </div>
    </div>

    <footer class="lesson-footer" v-if="isAuthenticated">
      <button v-if="!completed" class="cpub-btn-primary" @click="markComplete" :disabled="completing">
        {{ completing ? 'Marking...' : 'Mark as Complete' }}
      </button>
      <div v-else class="lesson-completed-badge">
        <i class="fa-solid fa-check-circle"></i> Completed
      </div>
      <NuxtLink :to="`/learn/${slug}`" class="cpub-btn-secondary">Back to Path</NuxtLink>
    </footer>
  </div>
  <div v-else class="not-found"><h1>Lesson not found</h1></div>
</template>

<style scoped>
.lesson-page { max-width: var(--content-max-width); }
.cpub-back-link { color: var(--accent); text-decoration: none; font-size: var(--text-sm); display: inline-block; margin-bottom: var(--space-4); }
.cpub-back-link:hover { text-decoration: underline; }
.lesson-header { margin-bottom: var(--space-6); }
.lesson-type { font-size: var(--text-xs); color: var(--accent); text-transform: capitalize; font-weight: var(--font-weight-medium); }
.lesson-title { font-size: var(--text-2xl); font-weight: var(--font-weight-bold); margin: var(--space-2) 0; }
.lesson-duration { font-size: var(--text-sm); color: var(--text-faint); }
.lesson-content { min-height: 200px; }
.lesson-empty { color: var(--text-faint); font-size: 13px; text-align: center; padding: 48px 0; display: flex; flex-direction: column; align-items: center; gap: 8px; }
.lesson-video { margin: 16px 0; }
.lesson-completed-badge { display: inline-flex; align-items: center; gap: 6px; color: var(--green); font-size: 13px; font-weight: 600; }
.cpub-btn-secondary { display: inline-block; padding: 6px 14px; border: 2px solid var(--border); background: var(--surface); color: var(--text); font-size: 12px; text-decoration: none; cursor: pointer; margin-left: 8px; }
.cpub-btn-secondary:hover { background: var(--surface2); }
.lesson-footer { margin-top: var(--space-6); padding-top: var(--space-4); border-top: 1px solid var(--border); }
.cpub-btn-primary { padding: var(--space-2) var(--space-4); background: var(--accent); color: var(--color-on-primary); border: 1px solid var(--border); font-size: var(--text-sm); font-weight: var(--font-weight-medium); font-family: var(--font-sans); cursor: pointer; }
.cpub-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
.cpub-btn-primary:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
.not-found { text-align: center; padding: var(--space-10) 0; color: var(--text-dim); }
</style>
