// apps/reference/pages/hubs/[slug]/members.vue
<script setup lang="ts">
const route = useRoute();
const slug = computed(() => route.params.slug as string);

const { data: members } = await useFetch(() => `/api/hubs/${slug.value}/members`);

useSeoMeta({
  title: () => `Members — CommonPub`,
});
</script>

<template>
  <div class="members-page">
    <h1 class="members-title">Members</h1>
    <NuxtLink :to="`/hubs/${slug}`" class="cpub-back-link">Back to community</NuxtLink>

    <div class="members-list" v-if="members?.length">
      <div class="member-card" v-for="m in members" :key="m.userId">
        <div class="member-info">
          <NuxtLink :to="`/u/${m.user.username}`" class="member-name">
            {{ m.user.displayName || m.user.username }}
          </NuxtLink>
          <span class="member-role">{{ m.role }}</span>
        </div>
        <time class="member-joined">Joined {{ new Date(m.joinedAt).toLocaleDateString() }}</time>
      </div>
    </div>
    <p class="members-empty" v-else>No members yet.</p>
  </div>
</template>

<style scoped>
.members-page {
  max-width: var(--content-max-width);
}

.members-title {
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--space-2);
}

.cpub-back-link {
  color: var(--accent);
  text-decoration: none;
  font-size: var(--text-sm);
  display: inline-block;
  margin-bottom: var(--space-6);
}

.cpub-back-link:hover {
  text-decoration: underline;
}

.member-card {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: var(--space-3);
  border-bottom: 1px solid var(--border);
}

.member-info {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.member-name {
  color: var(--text);
  text-decoration: none;
  font-weight: var(--font-weight-medium);
}

.member-name:hover {
  color: var(--accent);
}

.member-role {
  font-size: var(--text-xs);
  color: var(--accent);
  text-transform: capitalize;
}

.member-joined {
  font-size: var(--text-xs);
  color: var(--text-faint);
}

.members-empty {
  color: var(--text-faint);
  text-align: center;
  padding: var(--space-8) 0;
}
</style>

// apps/reference/src/routes/(app)/communities/[slug]/members/+page.svelte
<script lang="ts">
  import CommunityHeader from '$lib/components/community/CommunityHeader.svelte';
  import CommunityNav from '$lib/components/community/CommunityNav.svelte';
  import MemberCard from '$lib/components/community/MemberCard.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
</script>

<svelte:head>
  <title>Members — {data.community.name} — Snaplify</title>
</svelte:head>

<div class="members-page">
  <CommunityHeader community={data.community} />
  <CommunityNav slug={data.community.slug} active="members" role={data.community.currentUserRole} />

  <div class="members-list">
    {#if data.members.length === 0}
      <div class="empty-state">
        <p>No members yet.</p>
      </div>
    {:else}
      {#each data.members as member (member.userId)}
        <MemberCard {member} />
      {/each}
    {/if}
  </div>
</div>

<style>
  .members-page {
    max-width: var(--layout-content-width, 960px);
    margin: 0 auto;
  }

  .members-list {
    display: flex;
    flex-direction: column;
    gap: 1px;
    background: var(--color-border, #e5e5e5);
    border: 1px solid var(--color-border, #e5e5e5);
    border-radius: var(--radius-md, 6px);
    overflow: hidden;
  }

  .empty-state {
    text-align: center;
    padding: var(--space-xl, 3rem);
    color: var(--color-text-secondary, #666);
    background: var(--color-surface, #ffffff);
  }
</style>
