// apps/reference/pages/hubs/create.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' });

useSeoMeta({
  title: 'Create Hub — CommonPub',
  description: 'Create a new maker hub.',
});

const name = ref('');
const description = ref('');
const saving = ref(false);
const error = ref('');

async function handleCreate(): Promise<void> {
  saving.value = true;
  error.value = '';
  try {
    const result = await $fetch('/api/hubs', {
      method: 'POST',
      body: { name: name.value, description: description.value },
    });
    await navigateTo(`/hubs/${(result as { slug: string }).slug}`);
  } catch (err: unknown) {
    error.value = (err as { data?: { message?: string } })?.data?.message || 'Failed to create hub.';
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="create-community-page">
    <h1 class="page-title">Create Hub</h1>

    <form class="community-form" @submit.prevent="handleCreate" aria-label="Create community form">
      <div v-if="error" class="form-error" role="alert">{{ error }}</div>

      <div class="form-field">
        <label for="community-name" class="form-label">Name</label>
        <input id="community-name" v-model="name" type="text" class="form-input" required placeholder="Hub name" />
      </div>

      <div class="form-field">
        <label for="community-desc" class="form-label">Description</label>
        <textarea id="community-desc" v-model="description" class="form-textarea" rows="3" placeholder="What is this community about?" />
      </div>

      <button type="submit" class="cpub-btn-primary" :disabled="saving || !name">
        {{ saving ? 'Creating...' : 'Create Hub' }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.create-community-page {
  max-width: 600px;
}

.page-title {
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--space-6);
}

.community-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.form-error {
  padding: var(--space-3);
  background: var(--red-bg, var(--surface2));
  color: var(--red, var(--text));
  border: 1px solid var(--red, var(--border));
  font-size: var(--text-sm);
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.form-label {
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
}

.form-input,
.form-textarea {
  padding: var(--space-2) var(--space-3);
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--text);
  font-size: var(--text-base);
  font-family: var(--font-sans);
}

.form-input:focus,
.form-textarea:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: var(--focus-ring);
}

.form-textarea {
  resize: vertical;
}

.cpub-btn-primary {
  padding: var(--space-2) var(--space-4);
  background: var(--accent);
  color: var(--color-on-primary);
  border: 1px solid var(--border);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  font-family: var(--font-sans);
  cursor: pointer;
  align-self: flex-start;
}

.cpub-btn-primary:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.cpub-btn-primary:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}
</style>

// apps/reference/src/routes/(app)/communities/create/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import type { ActionData } from './$types';

  let { form }: { form: ActionData } = $props();
</script>

<svelte:head>
  <title>Create Community — Snaplify</title>
</svelte:head>

<div class="create-page">
  <h1>Create Community</h1>

  {#if form?.error}
    <div class="error-banner" role="alert">{form.error}</div>
  {/if}

  <form method="POST" use:enhance class="create-form">
    <div class="form-field">
      <label for="name">Name</label>
      <input
        type="text"
        id="name"
        name="name"
        required
        maxlength="128"
        placeholder="My Awesome Community"
      />
    </div>

    <div class="form-field">
      <label for="description">Description</label>
      <textarea
        id="description"
        name="description"
        maxlength="2000"
        rows="3"
        placeholder="What is this community about?"
      ></textarea>
    </div>

    <div class="form-field">
      <label for="rules">Rules</label>
      <textarea
        id="rules"
        name="rules"
        maxlength="10000"
        rows="5"
        placeholder="Community guidelines and rules..."
      ></textarea>
    </div>

    <div class="form-field">
      <label for="joinPolicy">Join Policy</label>
      <select id="joinPolicy" name="joinPolicy">
        <option value="open">Open — Anyone can join</option>
        <option value="approval">Approval — Invite token required</option>
        <option value="invite">Invite Only — Invite token required</option>
      </select>
    </div>

    <button type="submit" class="btn btn-primary">Create Community</button>
  </form>
</div>

<style>
  .create-page {
    max-width: var(--layout-content-width, 640px);
    margin: 0 auto;
  }

  h1 {
    font-size: var(--font-size-2xl, 1.875rem);
    color: var(--color-text, #1a1a1a);
    margin-bottom: var(--space-lg, 2rem);
  }

  .create-form {
    display: flex;
    flex-direction: column;
    gap: var(--space-md, 1rem);
  }

  .form-field {
    display: flex;
    flex-direction: column;
    gap: var(--space-xs, 0.25rem);
  }

  .form-field label {
    font-weight: var(--font-weight-medium, 500);
    color: var(--color-text, #1a1a1a);
    font-size: var(--font-size-sm, 0.875rem);
  }

  .form-field input,
  .form-field textarea,
  .form-field select {
    padding: var(--space-sm, 0.5rem) var(--space-md, 1rem);
    border: 1px solid var(--color-border, #e5e5e5);
    border-radius: var(--radius-md, 6px);
    font-size: var(--font-size-md, 1rem);
    background: var(--color-surface, #ffffff);
    color: var(--color-text, #1a1a1a);
  }

  .error-banner {
    padding: var(--space-sm, 0.5rem) var(--space-md, 1rem);
    background: var(--color-error-bg, #fef2f2);
    color: var(--color-error, #dc2626);
    border-radius: var(--radius-md, 6px);
    margin-bottom: var(--space-md, 1rem);
  }

  .btn {
    padding: var(--space-sm, 0.5rem) var(--space-md, 1rem);
    border: none;
    border-radius: var(--radius-md, 6px);
    font-size: var(--font-size-md, 1rem);
    cursor: pointer;
  }

  .btn-primary {
    background: var(--color-primary, #2563eb);
    color: var(--color-on-primary, #ffffff);
  }
</style>
